version: '3.9'
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./reactApp:/usr/src/app
    command: sh -c "cd react-dev && yarn start"
    ports:
      - "3000:3000"